# File: src/main/resources/application.properties

# Server port
server.port=8080

# Application name
spring.application.name=crud-app

# JSON formatting
spring.jackson.serialization.indent_output=true

# Static resources location



# ================================
# PostgreSQL Database Configuration
# ================================

spring.datasource.url=jdbc:postgresql://localhost:5432/cruddb
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
